name: Standards

on:
   pull_request:


jobs:
   standards:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
           with:
              # We need all the commits for commitlint to work
              fetch-depth: 0
         - name: Use Node.js 16.*
           uses: actions/setup-node@v1
           with:
              node-version: 16.*
         - name: Package Install
           run: npm ci
         - name: Standards
           run: npm run standards
         - name: Build
           run: npm run build
